[tool.poetry]
name = "removing access keys "
version = "0.1.0"
description = "Script to disable or delete access keys "
authors = ["Arun240726 <arun.kumarg@amagi.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
boto3 = ">=1.35.10"
